### ISSUE TITLE
[Enhancement] Ingress template should support a default backend

### ISSUE THREAD

**Issue by sjedlick** [T-Systems-MMS/helm-charts#47]
### Description

Ingress template should support the configuration of a default backend.

For example:
```
spec:
  defaultBackend:
    service:
      name: _servicename_
      port:
        number: _xxxx_

```

### Additional information

...
